### ISSUE TITLE
main quest npc sp_cor,255,285 miss

### ISSUE THREAD

**Issue by Angelic234** [crazy-arashi/rathena-script-collection#6]
https://github.com/crazy-arashi/Rathena-Script-Collection/blob/b260a5a5d308d7d3bbbe31b97ea5ad3678f42515/Episode%2017.1%20-%20Illusion/17.1_Quest.c#L7020-L7023

Player can't found NPC sp_cor,255,285 Rookie , so if ep_illusion = 46 main quest unable to continue

**Comment by admkakaroto** [comment]
@Angelic234 do you have an fix for this?
